name: bypass_app
description: Bypass JSON parser app by eri
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  vpn_connection_detector: ^2.1.0
  connectivity_plus: ^7.2.0
  shared_preferences: ^2.3.0
  share_plus: ^10.0.0
  flutter_local_notifications: ^17.2.3
  ffi: ^2.1.3
  photo_manager: ^3.6.0
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true